- name: Phase 5 - Manage nginx service
  hosts: all
  become: true

  tasks:
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Stop nginx
      service:
        name: nginx
        state: stopped
